project:
  type: website
  output-dir: docs
  render:
    - '*.qmd'

website:
  title: "Study-Sheet: Linear Algebra"
  sidebar:
    search: true
    tools:
      - icon: quizlet
        href: https://quizlet.com/explanations/textbook-solutions/linear-algebra-and-its-applications-5th-edition-9780321982384?funnelUUID=06d4ef46-c8b7-4ebd-b80a-08d311a6cdc7
  navbar:
    left:
    - href: index.qmd
      text: Concept Connections
    - href: class.qmd
      text: Class Schedule 
    - text: Exam 4
      menu: 
        - href: exam4/chapter5_3.qmd
          text: Chapter 5.3 (Diagonality)
        - href: exam4/chapter6_1.qmd
          text: Chapter 6.1 (Orthogonality)
        - href: exam4/chapter6_2.qmd
          text: Chapter 6.2 (Orthogonal Sets)
        - href: exam4/chapter6_3.qmd
          text: Chapter 6.3 (Orthogonal Projections)
        - href: exam4/chapter6_5.qmd
          text: Chapter 6.5 (Least squares problem)
    - text: Exam 3
      menu:
        - href: exam3/notecard_topics.qmd
          text: Exam 3 - Notecard
        - href: exam3/daily_review.qmd
          text: Exam 3 - Critical Foundations
        - href: exam3/semi_daily_review.qmd
          text: Exam 3 - Important Applications
        - href: exam3/every_three_days_review.qmd
          text: Exam 3 - Supporting Topics
    - text: Topics
      menu:
        - href: general_topics/vector_spaces_and_dimensions.qmd
          text: Vector Spaces and Dimensions
        - href: general_topics/null_spaces_col_spaces.qmd
          text: Null Space and Column Space
        - href: general_topics/eigenvalues_eigenvectors.qmd
          text: Eigenvalues and Eigenvectors
        - href: general_topics/linear_independence_and_span.qmd
          text: Linear Independence and Span
        - href: general_topics/matrix_transformations.qmd
          text: Matrix Transformations
        - href: general_topics/linear_equations.qmd
          text: Basic Linear Equations
        - href: general_topics/determinants.qmd
          text: Determinants
        - href: general_topics/rank.qmd
          text: Rank
        - href: general_topics/predicting_the_future.qmd
          text: Predicting the Future

            

format:
  html:
    theme:
      light: lightly
      dark: darkly
    css: styles.css
    page-layout: full
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: 'Show the code'
    code-overflow: wrap
    code-copy: hover
    code-tools:
      source: false
      toggle: true
      caption: See code
