---
title: "Class Schedule"
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    html-math-method: katex
---

| Class Date | Preparation                     | Class | Homework                                                                                         | Homework Due Dates                                    |
|------------|----------------------------------|-------|--------------------------------------------------------------------------------------------------|------------------------------------------------------|
| 9/16       | Intro and 1.1                  |       | 1, 2, 5, 7, 9, 13, 17, 19, 23, 24, 31; Self Testing 1.1                                         |                                                      |
| 9/18       | Do Self Testing 1.1; read 1.2  | 1.2   | 1, 3, 4, 5, 7, 8, 12, 14, 16, 17, 24, 29; S.T. 1.2                                             | 1.1 due                                              |
| 9/20       | Do Self Testing 1.2; read 1.3  | 1.3   | 3, 5, 7, 9, 12, 13, 15, 19, 24, 25; S.T. 1.3                                                  | 1.2 due                                              |
| 9/23       | Etc. as above                  | 1.4   | 1, 3, 5, 7, 10, 12, 13, 15, 22, 25, 26, 32, 40 (use Mathematica for 40); S.T. 1.4             |                                                      |
| 9/25       |                                | 1.5   | 3, 5, 7, 11, 15, 20, 23, 25, 29, 30, 35; S.T. 1.5                                             | 1.3, 1.4 due                                        |
| 9/27       |                                | 1.7   | 1, 3, 4, 7, 16, 18, 20, 21, 26, 33, 36; S.T. 1.7                                              | 1.5 due                                              |
| 9/30       | Exam Review                    |       | Exam 1 (Monday-Wednesday)                                                                      |                                                      |
| 10/2       |                                | 1.6   | None                                                                                           | 1.7 due                                              |
| 10/4       |                                | 1.8   | 1, 5, 8, 9, 13, 14, 17, 21, 29, 31, 39; S.T. 1.8                                              |                                                      |
| 10/7       |                                | 1.9   | 3, 8, 16, 19, 27, 29, 31, 32, 35; S.T. 1.9                                                   | 1.8 due                                              |
| 10/9       |                                | 2.1   | 1, 3, 6, 7, 10, 11, 12, 16, 22 (hint: use the definition of linear dependence), 27            |                                                      |
| 10/11      |                                | 2.2   | 1, 3, 6, 8, 9, 13, 14, 18, 23, 29, 32; S.T. 2.2                                              | 1.9 due                                              |
| 10/14      |                                | 2.3   | 2, 4, 5, 11, 13, 15, 16, 17, 28, 31, 33; S.T. 2.3                                            | 2.1, 2.2 due                                         |
| 10/16      | Python and 2.4                 | 2.4   | 1, 7, 10, 13, 17, 21; Programming hwk 1                                                     |                                                      |
| 10/18      |                                | 3.1   | 1, 2, 9, 12, 15, 19, 20, 21, 37                                                              | 2.3 due                                              |
| 10/21      |                                | 3.2   | 1, 2, 3, 5, 9, 15, 18, 21, 24, 31, 40, 41; S.T. 3.2                                          | 2.4, Programming hwk 1, and 3.1 due                 |
| 10/23      | Exam Review                    |       | 3.2 due; Exam 2 (Wed-Fri)                                                                    |                                                      |
| 10/25      | Test Day                       |       | Exam 2                                                                                       |                                                      |
| 10/28      |                                | 4.1   | 1, 3, 6, 7, 8, 9, 11, 13, 15, 17, 21, 26; S.T. 4.1                                          |                                                      |
| 10/30      |                                | 4.1   |                                                                                              |                                                      |
| 11/1       |                                | 4.2   | 2, 3, 5, 7, 8, 18, 21, 23, 26 (no justification needed), 33; S.T. 4.2                       | 4.1 due                                              |
| 11/4       |                                | 4.3   | 1, 2, 8, 13, 14, 19, 22 (a, b, c), 29, 30, 33; S.T. 4.3                                      | 4.2 due                                              |
| 11/6       |                                | 4.4   | 1, 3, 6, 7, 9, 11, 27, 32                                                                   |                                                      |
| 11/8       |                                | 4.5   | 1, 10, 11, 13, 14, 17, 21, 28 (hint: consider a subspace that we have looked at several times), | 4.3 due                                              |
|            |                                |       | 29, 30 (use a computer/calculator if needed); S.T. 4.5                                       |                                                      |
| 11/11      |                                | 4.6   | 1, 2, 5, 6, 7, 8, 15, 19, 26, 31; S.T. 4.6                                                  | 4.4, 4.5 due                                         |
| 11/13      |                                | 4.9   | 2, 3, 5, 9, 12, 13; S.T. 4.9                                                                |                                                      |
| 11/15      |                                | 5.1   | 3, 6, 9, 14, 17, 19, 23, 25, 26, 27, 29; S.T. 5.1; Programming 2                             | 4.6, 4.9 due                                         |
| 11/18      |                                | 5.2   | 1, 3, 7, 11, 15, 16, 18, 19, 20, 24; S.T. 5.2                                               | 5.1 due                                              |
| 11/20      |                                | 5.3   | 1, 6, 7, 9, 12, 21, 25, 27, 31                                                             |                                                      |
| 11/22      | Review                         |       | Exam Review; Programming hwk 2 due; 5.3 due (Exam Fri-Tues)                                  |                                                      |
| 11/25      | Exam Day                       |       | Exam 3 (covers 4.1-4.9)                                                                      |                                                      |
| 11/27-29   | Holiday                        |       |                                                                                              |                                                      |
| 12/2       |                                | 6.1   | 1, 5, 7, 9, 11, 14, 15, 16, 19, 28, 30; S.T. 6.1                                           |                                                      |
| 12/4       |                                | 6.2   | 1, 5, 7, 11, 14, 17, 23 (a, b, c), 27; S.T. 6.2                                             | 6.1 due                                              |
| 12/6       |                                | 6.3   | 1, 5, 8, 12, 16, 19, 21 (a, b, c, d)                                                        | 6.2 due                                              |
| 12/9       |                                | 6.4   | 3, 5, 7, 9, 17, 19                                                                          |                                                      |
| 12/11      |                                | 6.5   | 1, 3, 5, 7, 13, 17                                                                          | 6.3 due                                              |
| 12/13      |                                | 6.6   | 1, 3, 5, 8 (recommend using Python for calculations); S.T. 6.6                               | 6.4, 6.5 due                                         |
| 12/16      | Exam Review                    |       |                                                                                              | 6.6 due                                              |
| 12/17-18   | University Testing Days        |       | Exam 4 (Mon-Wed); Final is ~50% new (chpt 5, 6) and 50% old                                  |                                                      |
